@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.example.generator.manager.filemanager.FileManager#generate(FileType,List,String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "BothDirections" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.example.generator.manager.filemanager.FileManager",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_2052603225 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main1526836320XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_331531087 { 
   	label=generator
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1184093515 { 
   	label=XmlGenerator
	labeljust=l
	fillcolor=white
	style=filled
   
   XmlGenerator803829963XXXgenerate1182736675[
	label="+ generate()"
	style=filled
	fillcolor=white
	tooltip="XmlGenerator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_122187850 { 
   	label=FileManager
	labeljust=l
	fillcolor=white
	style=filled
   
   FileManager250475847XXXgenerate2011807411[
	label="+ generate()"
	style=filled
	fillcolor=white
	tooltip="FileManager

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1361567047 { 
   	label=JsonGenerator
	labeljust=l
	fillcolor=white
	style=filled
   
   JsonGenerator850663818XXXgenerate1182736675[
	label="+ generate()"
	style=filled
	fillcolor=white
	tooltip="JsonGenerator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_179284866 { 
   	label=GeneratorData
	labeljust=l
	fillcolor=white
	style=filled
   
   GeneratorData1538492109XXXsortValues532857393[
	label="+ sortValues()"
	style=filled
	fillcolor=white
	tooltip="GeneratorData

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1930731497 { 
   	label=CsvGenerator
	labeljust=l
	fillcolor=white
	style=filled
   
   CsvGenerator803849948XXXgenerate1182736675[
	label="+ generate()"
	style=filled
	fillcolor=white
	tooltip="CsvGenerator

null"
	fontcolor=darkgreen
];

CsvGenerator803849948XXXgetColTitles1361180454[
	label="+ getColTitles()"
	style=filled
	fillcolor=white
	tooltip="CsvGenerator

null"
	fontcolor=darkgreen
];

CsvGenerator803849948XXXgetRowValues1361180454[
	label="+ getRowValues()"
	style=filled
	fillcolor=white
	tooltip="CsvGenerator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2075899856 { 
   	label=FileGenerator
	labeljust=l
	fillcolor=white
	style=filled
   
   FileGenerator250475847XXXchooseGenerator2011807411[
	label="+ chooseGenerator()"
	style=filled
	fillcolor=white
	tooltip="FileGenerator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_263940583 { 
   	label=YamlGenerator
	labeljust=l
	fillcolor=white
	style=filled
   
   YamlGenerator851093321XXXgenerate1182736675[
	label="+ generate()"
	style=filled
	fillcolor=white
	tooltip="YamlGenerator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_451812021 { 
   	label=ExcelGenerator
	labeljust=l
	fillcolor=white
	style=filled
   
   ExcelGenerator596294229XXXfieldToCellType67875034[
	label="+ fieldToCellType()"
	style=filled
	fillcolor=white
	tooltip="ExcelGenerator

null"
	fontcolor=darkgreen
];

ExcelGenerator596294229XXXgenerate1182736675[
	label="+ generate()"
	style=filled
	fillcolor=white
	tooltip="ExcelGenerator

null"
	fontcolor=darkgreen
];

ExcelGenerator596294229XXXgetColTitles786659881[
	label="+ getColTitles()"
	style=filled
	fillcolor=white
	tooltip="ExcelGenerator

null"
	fontcolor=darkgreen
];

ExcelGenerator596294229XXXgetRowValues786659881[
	label="+ getRowValues()"
	style=filled
	fillcolor=white
	tooltip="ExcelGenerator

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
CsvGenerator803849948XXXgenerate1182736675 -> CsvGenerator803849948XXXgetColTitles1361180454;
CsvGenerator803849948XXXgenerate1182736675 -> CsvGenerator803849948XXXgetRowValues1361180454;
ExcelGenerator596294229XXXgenerate1182736675 -> ExcelGenerator596294229XXXgetColTitles786659881;
ExcelGenerator596294229XXXgenerate1182736675 -> ExcelGenerator596294229XXXgetRowValues786659881;
ExcelGenerator596294229XXXgetRowValues786659881 -> ExcelGenerator596294229XXXfieldToCellType67875034;
FileGenerator250475847XXXchooseGenerator2011807411 -> CsvGenerator803849948XXXgenerate1182736675;
FileGenerator250475847XXXchooseGenerator2011807411 -> ExcelGenerator596294229XXXgenerate1182736675;
FileGenerator250475847XXXchooseGenerator2011807411 -> GeneratorData1538492109XXXsortValues532857393;
FileGenerator250475847XXXchooseGenerator2011807411 -> JsonGenerator850663818XXXgenerate1182736675;
FileGenerator250475847XXXchooseGenerator2011807411 -> XmlGenerator803829963XXXgenerate1182736675;
FileGenerator250475847XXXchooseGenerator2011807411 -> YamlGenerator851093321XXXgenerate1182736675;
FileManager250475847XXXgenerate2011807411 -> FileGenerator250475847XXXchooseGenerator2011807411;
Main1526836320XXXmain1859653459 -> FileManager250475847XXXgenerate2011807411;
    
}
@enduml